export const ASK_QUESTION_STARTED='ASK_QUESTION_STARTED'
export const ASK_QUESTION_SUCCESS='ASK_QUESTION_SUCCESS'
export const ASK_QUESTION_ERROR='ASK_QUESTION_ERROR'
export const ASK_QUESTION_REMOVE_MESSAGE='ASK_QUESTION_REMOVE_MESSAGE'
export const DELETE_QUESTION_STARTED='DELETE_QUESTION_STARTED'
export const DELETE_QUESTION_SUCCESS='DELETE_QUESTION_SUCCESS'
export const DELETE_QUESTION_ERROR='DELETE_QUESTION_ERROR'



