export const NOTIFICATION_STARTED = "NOTIFICATION_STARTED";
export const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";
export const NOTIFICATION_VIEW='NOTIFICATION_VIEW'
export const SINGLE_NOTIFICATION_SUCCESS = "SINGLE_NOTIFICATION_SUCCESS";
export const CHANGED_NOTIFICATION_NUMBER = "CHANGED_NOTIFICATION_NUMBER";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
export const NOTIFICATION_ERROR = "NOTIFICATION_ERROR";
export const CHAT_NOTIFICATION_NUMBER = "CHAT_NOTIFICATION_NUMBER";
export const CHAT_NOTIFICATION_NUMBER_CHANGE =
  "CHAT_NOTIFICATION_NUMBER_CHANGE";