export const RESET_PASSWORD_REQUEST_STARTED = "RESET_PASSWORD_REQUEST_STARTED";
export const RESET_PASSWORD_REQUEST_SUCCESS = "RESET_PASSWORD_REQUEST_SUCCESS";
export const RESET_PASSWORD_REQUEST_ERROR = "RESET_PASSWORD_REQUEST_ERROR";

