export const SAVED_QUESTION_STARTED='SAVED_QUESTION_STARTED'
export const SAVED_QUESTION_SUCCESS='SAVED_QUESTION_SUCCESS'
export const SAVED_QUESTION_ERROR='SAVED_QUESTION_ERROR'
export const SAVED_QUESTION_DELETE ="SAVED_QUESTION_DELETE"
