export const UPDATE_QUESTION_STARTED='UPDATE_QUESTION_STARTED'
export const UPDATE_QUESTION_LOADED='UPDATE_QUESTION_LOADED'
export const UPDATE_QUESTION_ERROR='UPDATE_QUESTION_ERROR'
export const UPDATE_QUESTION_UPDATED ="UPDATE_QUESTION_UPDATED"
export const UPDATE_POST_QUESTION_STARTED = 'UPDATE_POST_QUESTION_STARTED'
export const UPDATE_POST_QUESTION_SUCCESS = "UPDATE_POST_QUESTION_SUCCESS"
export const UPDATE_POST_QUESTION_ERROR = "UPDATE_POST_QUESTION_ERROR"
export const UPDATE_POST_QUESTION_REMOVE_MESSAGE = "UPDATE_POST_QUESTION_REMOVE_MESSAGE"

