export const ASK_QUESTION_STARTED='ASK_QUESTION_STARTED'
export const ASK_QUESTION_SUCCESS='ASK_QUESTION_SUCCESS'
export const ASK_QUESTION_ERROR='ASK_QUESTION_ERROR'
export const ASK_QUESTION_REMOVE_MESSAGE='ASK_QUESTION_REMOVE_MESSAGE'


