export const CHATROOM_LOADED = "CHATROOM_LOADED";
export const CHATROOM_SUCCESS = "CHATROOM_SUCCESS";
export const CHATROOM_ERROR = "CHATROOM_ERROR";
export const CHATROOM_UPDATE = "CHATROOM_UPDATE";
