export const EXPERTISE_EDIT_LOAD='EXPERTISE_EDIT_LOAD'
export const EXPERTISE_EDIT_SUCCESS='EXPERTISE_EDIT_SUCCESS'
export const EXPERTISE_EDIT_ERROR='EXPERTISE_EDIT_ERROR'
export const EXPERTISE_EDIT_TEMP='EXPERTISE_EDIT_TEMP'


