export const LOGIN_REQUEST_STARTED='LOGIN_REQUEST_STARTED'
export const LOGIN_REQUEST_SUCCESS='LOGIN_REQUEST_SUCCESS'
export const LOGIN_REQUEST_ERROR='LOGIN_REQUEST_ERROR'
export const REMOVE_ERROR= 'REMOVE_ERROR'


