export const ANSWERS_LOAD_START='ANSWERS_LOAD_START'
export const ANSWERS_LOAD_SUCCESS='ANSWERS_LOAD_SUCCESS'
export const ANSWERS_LOAD_ERROR='ANSWERS_LOAD_ERROR'
export const NEW_ANSWERS_ADDED='NEW_ANSWERS_ADDED'





