export const ANSWERS_LOAD_START='ANSWERS_LOAD_START'
export const ANSWERS_LOAD_SUCCESS='ANSWERS_LOAD_SUCCESS'
export const ANSWERS_LOAD_ERROR='ANSWERS_LOAD_ERROR'
export const ANSWERS_ADD_START='ANSWERS_ADD_START'
export const ANSWERS_ADD_ERROR='ANSWERS_ADD_ERROR'
export const ANSWERS_DELETE_START ="ANSWERS_DELETE_START"
export const ANSWERS_DELETE_SUCCESS ="ANSWERS_DELETE_SUCCESS"
export const ANSWERS_DELETE_ERROR ="ANSWERS_DELETE_ERROR"





