export const PROFILE_DATA_LOADING='PROFILE_DATA_LOADING'
export const PROFILE_DATA_SUCCESS='PROFILE_DATA_SUCCESS'
export const PROFILE_DATA_ERROR='PROFILE_DATA_ERROR'
export const RESET_USER_INFO="RESET_USER_INFO"
export const CHANGE_IMAGE="CHANGE_IMAGE"
export const START_IMAGE_UPLOAD="START_IMAGE_UPLOAD"
export const IMAGE_UPLOAD_SUCCESS="IMAGE_UPLOAD_SUCCESS"
export const EDIT_PROFILE_ON ="EDIT_PROFILE_ON"
export const EDIT_PROFILE_OFF ="EDIT_PROFILE_OFF"

 

  

