export const PROFILE_DATA_LOADING='PROFILE_DATA_LOADING'
export const PROFILE_DATA_SUCCESS='PROFILE_DATA_SUCCESS'
export const PROFILE_DATA_ERROR='PROFILE_DATA_ERROR'
export const RESET_USER_INFO="RESET_USER_INFO"
