export const WISHES_EDIT_LOAD='WISHES_EDIT_LOAD'
export const WISHES_EDIT_SUCCESS='WISHES_EDIT_SUCCESS'
export const WISHES_EDIT_ERROR='WISHES_EDIT_ERROR'
export const WISHES_EDIT_TEMP='WISHES_EDIT_TEMP'


